//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineWS.SalaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sala_VO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Sala_VO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Id_SalaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomSalaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoSalaField;
        
        private int Asientos_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id_Sala {
            get {
                return this.Id_SalaField;
            }
            set {
                if ((this.Id_SalaField.Equals(value) != true)) {
                    this.Id_SalaField = value;
                    this.RaisePropertyChanged("Id_Sala");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NomSala {
            get {
                return this.NomSalaField;
            }
            set {
                if ((object.ReferenceEquals(this.NomSalaField, value) != true)) {
                    this.NomSalaField = value;
                    this.RaisePropertyChanged("NomSala");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TipoSala {
            get {
                return this.TipoSalaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoSalaField, value) != true)) {
                    this.TipoSalaField = value;
                    this.RaisePropertyChanged("TipoSala");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Asientos_ID {
            get {
                return this.Asientos_IDField;
            }
            set {
                if ((this.Asientos_IDField.Equals(value) != true)) {
                    this.Asientos_IDField = value;
                    this.RaisePropertyChanged("Asientos_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SalaService.SalaServiceSoap")]
    public interface SalaServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametros del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSala", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CineWS.SalaService.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CineWS.SalaService.Sala_VO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CineWS.SalaService.Sala_VO[]))]
        CineWS.SalaService.GetSalaResponse GetSala(CineWS.SalaService.GetSalaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSala", ReplyAction="*")]
        System.Threading.Tasks.Task<CineWS.SalaService.GetSalaResponse> GetSalaAsync(CineWS.SalaService.GetSalaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Delete_SalaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_Sala", ReplyAction="*")]
        CineWS.SalaService.Delete_SalaResponse Delete_Sala(CineWS.SalaService.Delete_SalaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_Sala", ReplyAction="*")]
        System.Threading.Tasks.Task<CineWS.SalaService.Delete_SalaResponse> Delete_SalaAsync(CineWS.SalaService.Delete_SalaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sala del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Sala", ReplyAction="*")]
        CineWS.SalaService.Insert_SalaResponse Insert_Sala(CineWS.SalaService.Insert_SalaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Sala", ReplyAction="*")]
        System.Threading.Tasks.Task<CineWS.SalaService.Insert_SalaResponse> Insert_SalaAsync(CineWS.SalaService.Insert_SalaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSalaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSala", Namespace="http://tempuri.org/", Order=0)]
        public CineWS.SalaService.GetSalaRequestBody Body;
        
        public GetSalaRequest() {
        }
        
        public GetSalaRequest(CineWS.SalaService.GetSalaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSalaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CineWS.SalaService.ArrayOfAnyType parametros;
        
        public GetSalaRequestBody() {
        }
        
        public GetSalaRequestBody(CineWS.SalaService.ArrayOfAnyType parametros) {
            this.parametros = parametros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSalaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSalaResponse", Namespace="http://tempuri.org/", Order=0)]
        public CineWS.SalaService.GetSalaResponseBody Body;
        
        public GetSalaResponse() {
        }
        
        public GetSalaResponse(CineWS.SalaService.GetSalaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSalaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CineWS.SalaService.Sala_VO[] GetSalaResult;
        
        public GetSalaResponseBody() {
        }
        
        public GetSalaResponseBody(CineWS.SalaService.Sala_VO[] GetSalaResult) {
            this.GetSalaResult = GetSalaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Delete_SalaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Sala", Namespace="http://tempuri.org/", Order=0)]
        public CineWS.SalaService.Delete_SalaRequestBody Body;
        
        public Delete_SalaRequest() {
        }
        
        public Delete_SalaRequest(CineWS.SalaService.Delete_SalaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Delete_SalaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public Delete_SalaRequestBody() {
        }
        
        public Delete_SalaRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Delete_SalaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_SalaResponse", Namespace="http://tempuri.org/", Order=0)]
        public CineWS.SalaService.Delete_SalaResponseBody Body;
        
        public Delete_SalaResponse() {
        }
        
        public Delete_SalaResponse(CineWS.SalaService.Delete_SalaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Delete_SalaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Delete_SalaResult;
        
        public Delete_SalaResponseBody() {
        }
        
        public Delete_SalaResponseBody(string Delete_SalaResult) {
            this.Delete_SalaResult = Delete_SalaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Insert_SalaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert_Sala", Namespace="http://tempuri.org/", Order=0)]
        public CineWS.SalaService.Insert_SalaRequestBody Body;
        
        public Insert_SalaRequest() {
        }
        
        public Insert_SalaRequest(CineWS.SalaService.Insert_SalaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Insert_SalaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CineWS.SalaService.Sala_VO sala;
        
        public Insert_SalaRequestBody() {
        }
        
        public Insert_SalaRequestBody(CineWS.SalaService.Sala_VO sala) {
            this.sala = sala;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Insert_SalaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert_SalaResponse", Namespace="http://tempuri.org/", Order=0)]
        public CineWS.SalaService.Insert_SalaResponseBody Body;
        
        public Insert_SalaResponse() {
        }
        
        public Insert_SalaResponse(CineWS.SalaService.Insert_SalaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Insert_SalaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Insert_SalaResult;
        
        public Insert_SalaResponseBody() {
        }
        
        public Insert_SalaResponseBody(string Insert_SalaResult) {
            this.Insert_SalaResult = Insert_SalaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SalaServiceSoapChannel : CineWS.SalaService.SalaServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalaServiceSoapClient : System.ServiceModel.ClientBase<CineWS.SalaService.SalaServiceSoap>, CineWS.SalaService.SalaServiceSoap {
        
        public SalaServiceSoapClient() {
        }
        
        public SalaServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalaServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalaServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalaServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CineWS.SalaService.GetSalaResponse CineWS.SalaService.SalaServiceSoap.GetSala(CineWS.SalaService.GetSalaRequest request) {
            return base.Channel.GetSala(request);
        }
        
        public CineWS.SalaService.Sala_VO[] GetSala(CineWS.SalaService.ArrayOfAnyType parametros) {
            CineWS.SalaService.GetSalaRequest inValue = new CineWS.SalaService.GetSalaRequest();
            inValue.Body = new CineWS.SalaService.GetSalaRequestBody();
            inValue.Body.parametros = parametros;
            CineWS.SalaService.GetSalaResponse retVal = ((CineWS.SalaService.SalaServiceSoap)(this)).GetSala(inValue);
            return retVal.Body.GetSalaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CineWS.SalaService.GetSalaResponse> CineWS.SalaService.SalaServiceSoap.GetSalaAsync(CineWS.SalaService.GetSalaRequest request) {
            return base.Channel.GetSalaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CineWS.SalaService.GetSalaResponse> GetSalaAsync(CineWS.SalaService.ArrayOfAnyType parametros) {
            CineWS.SalaService.GetSalaRequest inValue = new CineWS.SalaService.GetSalaRequest();
            inValue.Body = new CineWS.SalaService.GetSalaRequestBody();
            inValue.Body.parametros = parametros;
            return ((CineWS.SalaService.SalaServiceSoap)(this)).GetSalaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CineWS.SalaService.Delete_SalaResponse CineWS.SalaService.SalaServiceSoap.Delete_Sala(CineWS.SalaService.Delete_SalaRequest request) {
            return base.Channel.Delete_Sala(request);
        }
        
        public string Delete_Sala(int id) {
            CineWS.SalaService.Delete_SalaRequest inValue = new CineWS.SalaService.Delete_SalaRequest();
            inValue.Body = new CineWS.SalaService.Delete_SalaRequestBody();
            inValue.Body.id = id;
            CineWS.SalaService.Delete_SalaResponse retVal = ((CineWS.SalaService.SalaServiceSoap)(this)).Delete_Sala(inValue);
            return retVal.Body.Delete_SalaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CineWS.SalaService.Delete_SalaResponse> CineWS.SalaService.SalaServiceSoap.Delete_SalaAsync(CineWS.SalaService.Delete_SalaRequest request) {
            return base.Channel.Delete_SalaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CineWS.SalaService.Delete_SalaResponse> Delete_SalaAsync(int id) {
            CineWS.SalaService.Delete_SalaRequest inValue = new CineWS.SalaService.Delete_SalaRequest();
            inValue.Body = new CineWS.SalaService.Delete_SalaRequestBody();
            inValue.Body.id = id;
            return ((CineWS.SalaService.SalaServiceSoap)(this)).Delete_SalaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CineWS.SalaService.Insert_SalaResponse CineWS.SalaService.SalaServiceSoap.Insert_Sala(CineWS.SalaService.Insert_SalaRequest request) {
            return base.Channel.Insert_Sala(request);
        }
        
        public string Insert_Sala(CineWS.SalaService.Sala_VO sala) {
            CineWS.SalaService.Insert_SalaRequest inValue = new CineWS.SalaService.Insert_SalaRequest();
            inValue.Body = new CineWS.SalaService.Insert_SalaRequestBody();
            inValue.Body.sala = sala;
            CineWS.SalaService.Insert_SalaResponse retVal = ((CineWS.SalaService.SalaServiceSoap)(this)).Insert_Sala(inValue);
            return retVal.Body.Insert_SalaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CineWS.SalaService.Insert_SalaResponse> CineWS.SalaService.SalaServiceSoap.Insert_SalaAsync(CineWS.SalaService.Insert_SalaRequest request) {
            return base.Channel.Insert_SalaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CineWS.SalaService.Insert_SalaResponse> Insert_SalaAsync(CineWS.SalaService.Sala_VO sala) {
            CineWS.SalaService.Insert_SalaRequest inValue = new CineWS.SalaService.Insert_SalaRequest();
            inValue.Body = new CineWS.SalaService.Insert_SalaRequestBody();
            inValue.Body.sala = sala;
            return ((CineWS.SalaService.SalaServiceSoap)(this)).Insert_SalaAsync(inValue);
        }
    }
}
